title: Minimalistic
logo: /assets/img/rcb.jpeg
description: Your Friendly Neighborhood Cosmologist
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: Email
    icon: <i class="fa fa-envelope" aria-hidden="true"></i>
    link: mailto:reginaldchristianbernardo@gmail.com
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/reggiebernardo
  - name: ORCID
    icon: <i class="fa-brands fa-orcid"></i>
    link: https://orcid.org/0000-0001-8589-6851

navigation:
  - name: Home
    link: ./index.html
  - name: Bio
    link: ./bio.html
  - name: Research
    link: ./research.html
    sublist:
      - name: Highlights
        link: ./research.html#highlights
  - name: Teaching
    link: ./teaching.html
  - name: Contact
    link: ./contact.html
    
